import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { Switch } from '../core/switch';
export function PreviewWheelHeaderControls({ items, rowTitle, isFirstGridRow = false, canNavigateBack = false, onNavigateBack, parentCollectionName, parentCollectionThumbnailUrl, breadcrumbs, onBreadcrumbClick, currentCollectionName, onBreakoutCollectionsChange, breakoutCollectionsEnabled = false, onBreakoutNestingDepthChange, breakoutNestingDepth = 1, onTimelineWrappedChange, timelineWrapped = false, }) {
    return (_jsxs("div", { className: "z-30 flex w-full shrink-0 items-center border-b border-zinc-800/60 bg-[#0c0c0e] px-4 py-2 shadow-md", children: [_jsxs("div", { className: "flex min-w-0 flex-1 items-center gap-3", children: [onNavigateBack && !isFirstGridRow && (_jsx("button", { type: "button", title: canNavigateBack ? (parentCollectionName ? `Back to ${parentCollectionName}` : 'Back to parent collection') : 'No parent collection', "aria-label": canNavigateBack ? (parentCollectionName ? `Back to ${parentCollectionName}` : 'Back to parent collection') : 'No parent collection', disabled: !canNavigateBack, onClick: (event) => {
                            event.stopPropagation();
                            onNavigateBack();
                        }, className: "group relative flex h-8 w-8 shrink-0 items-center justify-center overflow-hidden rounded-full border border-zinc-700 bg-zinc-800 text-zinc-300 transition-colors hover:border-zinc-500 hover:text-white disabled:opacity-40 disabled:cursor-not-allowed", children: canNavigateBack && parentCollectionThumbnailUrl ? (_jsxs(_Fragment, { children: [_jsx("img", { src: parentCollectionThumbnailUrl, alt: "", className: "absolute inset-0 h-full w-full object-cover opacity-60 transition-opacity duration-200 group-hover:opacity-80" }), _jsx("div", { className: "absolute inset-0 bg-black/40 transition-colors duration-200 group-hover:bg-black/25" }), _jsx(ArrowLeft, { className: "relative z-10 h-4 w-4 text-white drop-shadow-[0_1.5px_2px_rgba(0,0,0,0.85)] transition-transform duration-200 group-hover:-translate-x-0.5" })] })) : (_jsx(ArrowLeft, { className: "h-4 w-4" })) })), breadcrumbs && breadcrumbs.length > 0 ? (_jsx("div", { className: "flex min-w-0 items-center gap-1.5 overflow-hidden text-xs font-bold text-zinc-400 select-none", children: breadcrumbs.map((crumb, idx) => {
                            const isLast = idx === breadcrumbs.length - 1;
                            return (_jsxs(React.Fragment, { children: [idx > 0 && _jsx("span", { className: "text-zinc-600 text-[10px] select-none font-mono", children: "/" }), isLast ? (_jsx("span", { className: "text-zinc-100 font-black truncate max-w-[150px]", children: crumb.name })) : (_jsx("button", { type: "button", onClick: () => onBreadcrumbClick === null || onBreadcrumbClick === void 0 ? void 0 : onBreadcrumbClick(idx), className: "hover:text-zinc-200 transition-colors truncate max-w-[120px] font-black", children: crumb.name }))] }, crumb.id));
                        }) })) : (_jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[9px] font-bold uppercase tracking-widest text-zinc-500", children: rowTitle || 'Current Collection' }), _jsxs("span", { className: "text-xs font-black text-zinc-200", children: [currentCollectionName || 'Workspace', items && ` (${items.length})`] })] }))] }), _jsxs("div", { className: "ml-auto flex shrink-0 items-center gap-4 pl-4 text-[10px] font-bold uppercase tracking-wider text-zinc-400", children: [onBreakoutCollectionsChange && (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { children: "Break out by collection" }), _jsx(Switch, { size: "sm", checked: breakoutCollectionsEnabled, onCheckedChange: onBreakoutCollectionsChange, "aria-label": "Break out by collection" })] })), breakoutCollectionsEnabled && onBreakoutNestingDepthChange && (_jsxs("div", { className: "flex items-center gap-1.5 border border-zinc-800 bg-zinc-900/60 rounded px-1.5 py-0.5 text-[9px] text-zinc-300", children: [_jsx("span", { children: "Depth:" }), _jsxs("select", { value: breakoutNestingDepth, onChange: (e) => onBreakoutNestingDepthChange(Number(e.target.value)), className: "bg-transparent border-none text-zinc-100 font-bold focus:outline-none cursor-pointer", children: [_jsx("option", { value: "1", className: "bg-zinc-950 text-zinc-200", children: "1 Level" }), _jsx("option", { value: "2", className: "bg-zinc-950 text-zinc-200", children: "2 Levels" }), _jsx("option", { value: "3", className: "bg-zinc-950 text-zinc-200", children: "3 Levels" })] })] })), onTimelineWrappedChange && (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { children: "Wrap timeline" }), _jsx(Switch, { size: "sm", checked: timelineWrapped, onCheckedChange: onTimelineWrappedChange, "aria-label": "Wrap timeline" })] }))] })] }));
}
