// The package's only runtime export: the built MCP Apps view as an HTML string.
//
// `timeline-app-html.ts` is GENERATED by `npm run build` (vite build →
// build-html-module.mjs) and committed, so consumers can import it without
// running a build first. Re-exporting through this entry point means the Next
// route imports a PACKAGE rather than reaching across the workspace at a file
// path — and, more importantly, the HTML reaches the serverless bundle as a
// hard module dependency the bundler cannot fail to trace.

export { TIMELINE_APP_HTML } from "./timeline-app-html";
